services:
  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: react_frontend
    restart: always
    environment:
      - NODE_ENV=production
    expose:
      - "3000"

  # Backend service
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: node_backend
    restart: always
    environment:
      - NODE_ENV=production
    expose:
      - "5000"

      # MongoDB Service
  mongo:
    image: mongo:6
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_DATABASE: mydb
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    depends_on:
      - frontend
      - backend
      - certbot
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/entrypoint.sh:/entrypoint.sh:ro
      - ./nginx/templates:/etc/nginx/templates:ro
      - certbot_certs:/etc/letsencrypt
      - certbot_challenges:/var/www/certbot
    env_file:
      - .env
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot_ssl
    volumes:
      - certbot_certs:/etc/letsencrypt
      - certbot_challenges:/var/www/certbot
      - ./certbot/init.sh:/init.sh:ro
    env_file:
      - .env
    entrypoint: ["/bin/sh", "/init.sh"]
    restart: always

volumes:
  certbot_certs:
  certbot_challenges:
  mongo_data:
