name: Deploy to EC2

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Chekcout code
        uses: actions/checkout@v4

      # Test Docker build (CI test)
      - name: Build Docker image (CI Test)
        run: |
          docker build -t react-app .

      # Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USER}}
          key: ${{secrets.EC2_KEY}}
          script: | 
            set -e
            APP_DIR=~/todo_app

            echo "===== Checking if application is already installed ===="

            if [ -d "$APP_DIR" ]; then
              echo "ğŸŸ¨ App directory exists - updating application..."

              cd $APP_DIR/frontend

              echo "ğŸ‘‰ Pulling lastest code in frontend"
              git fetch origin production
              git reset --hard origin/production

              echo "ğŸŸ¢ Updating .env from Github secret..."
              if [ -f ".env" ]; then
                cp .env .env.backup_$(date +%s)
              fi
              echo "${{ secrets.FRONTEND_ENV_FILE }}" > .env

              echo "ğŸš€ Rebuilding and restarting application..."
              docker compose up --build -d

              echo "ğŸ§¹ Cleaning up unused images..."
              docker image prune -f

              echo "âœ… Frontend update complete!"
            else
              echo "ğŸŸ¨ App not found - running first-time setup..."

              echo "ğŸ“‚ Creating app directory..."
              mkdir -p $APP_DIR
              cd $APP_DIR

              echo "ğŸ§² Clong frontend repository..."
              git clone https://github.com/${{ github.repository }} frontend

              echo "ğŸ§² Clong backend repository..."
              git clone https://github.com/${{ github.repository_owner }}/${{ secrets.BACKEND_REPO_NAME }} backend

              echo "ğŸ‘‰ Creating .env file in backend..."
              cd backend 
              echo "${{ secrets.BACKEND_ENV_FILE}}" > .env

              echo "ğŸ‘‰ Creating .env file in frontend..."
              cd ../frontend
              echo "${{ secrets.FRONTEND_ENV_FILE}}" > .env

              echo "ğŸŸ Installing docker using install-docker.sh..."
              chmod +x install-docker.sh
              ./install-docker.sh

              echo "ğŸš€ Running application for the first time..."
              sudo docker compose up --build -d

              echo "ğŸ‰ First-time setup completed successfully!"
            fi


